// Generated by CodiumAI
import peanut from '../src/index' // import directly from source code
import { ethers } from 'ethersv5' // v5
import dotenv from 'dotenv'

dotenv.config()
describe('getAllCreatedLinksForAddress', () => {
	const RPC_URL_GOERLI = process.env.INFURA_GOERLI_RPC
	const PUB_KEY = '0xB6f42695E43712B091F398fe61562F0FDF44c973'

	it('should return all deposits for the given address', async () => {
		const chainId = '5'
		const address = PUB_KEY
		const provider = new ethers.providers.JsonRpcProvider(RPC_URL_GOERLI)
		const peanutContractVersion = 'v5'

		const allCreatedLinks = await peanut.getAllCreatedLinksForAddress({
			address,
			chainId,
			provider,
			peanutContractVersion,
		})

		expect(allCreatedLinks.length).toBeGreaterThan(0)
	}, 100000)

	it('should return all deposits for the given address if the provider is undefined', async () => {
		const chainId = '137'
		const address = PUB_KEY
		const peanutContractVersion = 'v4'

		peanut.toggleVerbose(true)

		const allCreatedLinks = await peanut.getAllCreatedLinksForAddress({
			address,
			chainId,
			peanutContractVersion,
		})

		expect(allCreatedLinks.length).toBeGreaterThan(0)
	}, 10000)

	it('should return all deposits for the given address if the peanutContractVersion is undefined', async () => {
		const chainId = '5'
		const address = PUB_KEY
		const provider = new ethers.providers.JsonRpcProvider(RPC_URL_GOERLI)

		peanut.toggleVerbose(true)

		const allCreatedLinks = await peanut.getAllCreatedLinksForAddress({
			address,
			chainId,
			provider,
		})

		expect(allCreatedLinks.length).toBeGreaterThan(0)
	})

	it('should return all deposits for the given address if the peanutContractVersion and provider are undefined', async () => {
		const chainId = '1'
		const address = PUB_KEY

		peanut.toggleVerbose(true)

		const allCreatedLinks = await peanut.getAllCreatedLinksForAddress({
			address,
			chainId,
		})

		expect(allCreatedLinks.length).toBeGreaterThan(0)
	})
})
